config/routes.rb
Rails.application.routes.draw do

  # get 'carts_item/create'
  # get 'carts_item/destroy'
  # get 'carts_item/add_quantity'
  # get 'carts_item/reduce_quantity'
  resources :items_images
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'items#index'

  devise_for :users

  get 'static_pages/index'
  get 'static_pages/secret'
  get 'pay_form', to: 'static_pages#pay_form'

  resources :items do
    resources :items_images, only: [:create]
  end
  resources :carts
  resources :orders
  resources :carts_item
  post 'carts_item/:id/add' => "carts_item#add_quantity", as: "cart_item_add"
  post 'carts_item/:id/reduce' => "cart_item#reduce_quantity", as: "cart_item_reduce"

end

app/models/items_image.rb
class ItemsImage < ApplicationRecord
end

app/controllers/items_images_controller.rb
class ItemsImagesController < ApplicationController
  before_action :set_items_image, only: [:show, :edit, :update, :destroy]

  # GET /items_images
  # GET /items_images.json
  def index
    @items_images = ItemsImage.all
  end

  # GET /items_images/1
  # GET /items_images/1.json
  def show
  end

  # GET /items_images/new
  def new
    @items_image = ItemsImage.new
  end

  # GET /items_images/1/edit
  def edit
  end

  # POST /items_images
  # POST /items_images.json
  def create
    @item = Item.find(params[:item_id])
    @item.item_image.attach(params[:item_image])
    redirect_to(item_path(@item))
  end

  # PATCH/PUT /items_images/1
  # PATCH/PUT /items_images/1.json
  def update
    respond_to do |format|
      if @items_image.update(items_image_params)
        format.html { redirect_to @items_image, notice: 'Items image was successfully updated.' }
        format.json { render :show, status: :ok, location: @items_image }
      else
        format.html { render :edit }
        format.json { render json: @items_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items_images/1
  # DELETE /items_images/1.json
  def destroy
    @items_image.destroy
    respond_to do |format|
      format.html { redirect_to items_images_url, notice: 'Items image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_items_image
      @items_image = ItemsImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def items_image_params
      params.fetch(:items_image, {})
    end
end

app/helpers/items_images_helper.rb
module ItemsImagesHelper
end

app/views/items_images/_form.html.erb
<%= form_with(model: items_image, local: true) do |form| %>
  <% if items_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(items_image.errors.count, "error") %> prohibited this items_image from being saved:</h2>

      <ul>
      <% items_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items_images/edit.html.erb
<h1>Editing Items Image</h1>

<%= render 'form', items_image: @items_image %>

<%= link_to 'Show', @items_image %> |
<%= link_to 'Back', items_images_path %>

app/views/items_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items Images</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items_images.each do |items_image| %>
      <tr>
        <td><%= link_to 'Show', items_image %></td>
        <td><%= link_to 'Edit', edit_items_image_path(items_image) %></td>
        <td><%= link_to 'Destroy', items_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Items Image', new_items_image_path %>

app/views/items_images/new.html.erb
<h1>New Items Image</h1>

<%= render 'form', items_image: @items_image %>

<%= link_to 'Back', items_images_path %>

app/views/items_images/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_items_image_path(@items_image) %> |
<%= link_to 'Back', items_images_path %>