config/routes.rb
Rails.application.routes.draw do

  # get 'carts_item/create'
  # get 'carts_item/destroy'
  # get 'carts_item/add_quantity'
  # get 'carts_item/reduce_quantity'
  resources :items_images
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'items#index'

  devise_for :users

  get 'static_pages/index'
  get 'static_pages/secret'
  get 'pay_form', to: 'static_pages#pay_form'

  resources :items do
    resources :items_images, only: [:create]
  end
  resources :carts
  resources :orders
  resources :carts_item
  post 'carts_item/:id/add' => "carts_item#add_quantity", as: "cart_item_add"
  post 'carts_item/:id/reduce' => "cart_item#reduce_quantity", as: "cart_item_reduce"

end

app/models/item.rb
class Item < ApplicationRecord

  has_many :carts_items, foreign_key: 'item_id', dependent: :nullify
  has_many :carts, through: :carts_items, source: :carts_id
  has_many :orders_items, foreign_key: 'item_id'
  has_many :orders, through: :orders_items, source: :orders_id

  has_one_attached :item_image

  validates :title,
    presence: true

  validates :description,
    presence: true

  validates :price,
    presence: true

  validates :image_url,
    presence: true

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @cart_item = CartsItem.new()
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_banner.html.erb
<div class="container-fluid">
  <div class="jumbotron">

  <h1 class="display-3">Welcome !</h1>
  <p class="lead">Boutique de vente en ligne de photos de chatons</p>

  </br>
  <p class="lead">
  <a class="btn btn-primary btn-md" href="#" role="button">Voir les photos</a>
  <a class="btn btn-secondary btn-md" href="<%= new_user_registration_path %>" role="button">Créer un profil</a>
  </p>
</div>
</div>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<%= render 'banner' %>

<div class="container center-div">

  <!--section card-->
  <h1 class="my-5 text-center">Cards</h1>
  </br>

  <div class="row">
    <% @items.each do |item| %>
    <!-- classe des cards-->
    <div class="card text-white bg-secondary mb-3 ml-3 mr-3" style="max-width: 20rem;">
      <!-- début de la 1ere card-->
      <div class="card-header"><%= item.title %></div>

        <%= image_tag("cats/#{item.image_url}", :class => "card-img-top")%>
   
        <!--  <%if item.item_image.attached?%>

        <%= image_tag(item.item_image, alt: 'image du chat', :class => "card-img-top") %>
        <%else%>
        <p>No picture yet !</p>
        <%end%>
        -->

      <div class="card-body">
        <p class="card-text"><center>
          <%= link_to 'Preview', item, :class => "btn btn-primary btn-sm" %>
          <%= link_to 'Shop now', carts_item_index_path(item_id: item), method: "create", :class => "btn btn-primary btn-sm" %>
      </div>
      <!-- fin de la première card -->
    </div>
    <% end %>
  </div>

</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<div class="container">

<p>
  <strong>Title:</strong>
 <h1> <%= @item.title %> </h1>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%if @item.item_image.attached?%>
  <%= image_tag @item.item_image, alt: 'image du chat', :class => "card-img-top" %>
  <%else%>
  <p>No picture yet !</p>
  <%end%>
</p>

<!-- ONLY ADMIN -->
<p>
  <strong>Add/Edit Image ?</strong>
  <%= form_tag item_items_images_path(@item), multipart: true do %>
  <%= file_field_tag :item_image %>
  <%= submit_tag "mettre à jour" %>
  <% end %>
</p>
<!-- FIN ONLY ADMIN -->

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>


</div>